// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Query struct {
}

type Wiki struct {
	Topic   string  `json:"topic"`
	Opening *string `json:"opening,omitempty"`
	Midgame *string `json:"midgame,omitempty"`
	Endgame *string `json:"endgame,omitempty"`
}
