networks:
  app-network:
    driver: bridge

services:
  soap-server:
    build:
      context: ./soap-service
      dockerfile: Dockerfile
    container_name: soap-server
    networks:
      - app-network
    ports:
      - "8080:80"

  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: chess_db
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network
    ports:
      - "3306:3306"

  flask-api:
    build:
      context: ./RestAPI
      dockerfile: Dockerfile
    container_name: flask-api
    ports:
      - "5000:5000"
    volumes:
      - ./RestAPI:/app
    networks:
      - app-network

  grpc-service:
    build:
      context: ./GrpcService
      dockerfile: Dockerfile
    container_name: grpc-service
    ports:
      - "8081:8080" # Changed to avoid conflict
    depends_on:
      - mysql-db
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=mysql-db;Database=chess_db;User=username;Password=password;
    networks:
      - app-network

  soap-adapter:
    build:
      context: ./soap-adapter
      dockerfile: Dockerfile
    container_name: soap-adapter
    ports:
      - "5001:5000" # Exposing port 5000 of the container to port 5001 on the host
    depends_on:
      - grpc-service
    networks:
      - app-network

  competition-service:
    build:
      context: ./competition-service
    ports:
      - "3000:3000"
    networks:
      - app-network

  mqtt-broker:
    image: eclipse-mosquitto
    container_name: mqtt-broker
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    networks:
      - app-network

  go-graphql-service:
    build: ./go-graphql-service
    container_name: go-graphql-service
    ports:
      - "4000:4000"
    networks:
      - app-network

  stockfishcontainer:
    build:
      context: ./stockfishcontainer
    container_name: stockfishcontainer
    ports:
      - "9000:9000"
    networks:
      - app-network



volumes:
  mysql-data: